FROM ghcr.io/astral-sh/uv:0.11.19-python3.12-trixie-slim
ENV UV_COMPILE_BYTECODE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    libsndfile1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY packages/shared/pyproject.toml packages/shared/
COPY packages/worker/pyproject.toml packages/worker/
ENV SOURCE_DATE_EPOCH=0
RUN uv sync --frozen --no-dev --no-install-project --package ragrat-worker

COPY packages/shared/ packages/shared/
COPY packages/worker/ packages/worker/
COPY ui/ ui/


EXPOSE 8000

CMD [\
    "uv", "run",\
    "--package", "ragrat-worker",\
    "--no-dev",\
    "fastapi", "run", "packages/worker/src/app.py", "--host", "0.0.0.0", "--port", "8000"\
]
