FROM ghcr.io/astral-sh/uv:python3.12-trixie-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY packages/shared/ packages/shared/
COPY packages/indexer/ packages/indexer/

RUN uv sync --frozen --no-dev --no-install-project

EXPOSE 8000

CMD ["uv", "run", "--no-dev", "fastapi", "run", "packages/indexer/app.py", "--host", "0.0.0.0", "--port", "8000"]
