FROM ghcr.io/astral-sh/uv:0.11.19-python3.12-trixie-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY packages/shared/pyproject.toml packages/shared/
COPY packages/indexer/pyproject.toml packages/indexer/
RUN uv sync --frozen --no-dev --no-install-project --package ragrat-indexer

COPY packages/shared/ packages/shared/
COPY packages/indexer/ packages/indexer/

EXPOSE 8000

CMD [\
    "uv", "run",\
    "--package", "ragrat-indexer",\
    "--no-dev",\
    "fastapi", "run", "packages/indexer/src/app.py", "--host", "0.0.0.0", "--port", "8000"\
]
