services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # HTTP API & Web UI Dashboard
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage:z
    restart: always
  # weaviate:
  #   image: cr.weaviate.io/semitechnologies/weaviate:1.37.7
  #   restart: unless-stopped
  #   ports:
  #     - "11480:8080"
  #     - "50051:50051"
  #   environment:
  #     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
  #     AUTHENTICATION_APIKEY_ENABLED: "true"
  #     AUTHENTICATION_APIKEY_ALLOWED_KEYS: $WEAVIATE_API_KEY
  #     AUTHENTICATION_APIKEY_USERS: "admin"
  #     AUTHORIZATION_ADMIN_LIST_ENABLED: "true"
  #     PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
  #     DISK_USE_WARNING_THRESHOLD: 0.95
  #     DISK_USE_CRITICAL_THRESHOLD: 0.99
  #     ENABLE_MODULES: "text2vec-transformers"
  #     TRANSFORMERS_INFERENCE_API: http://text2vec-transformers:8080
  #     CLUSTER_HOSTNAME: "node1"
  #   volumes:
  #     - weaviate_data:/var/lib/weaviate
  #     - .cache:/root/.cache

  # text2vec-transformers:
  #   image: ghcr.io/itmo-call-center-assistant/ragrat/text2vec:user2-base-latest
  #   environment:
  #     MODEL_NAME: "deepvk/USER2-base"
  #     ENABLE_CUDA: "0" # Set to 1 if you have a GPU
  #   volumes:
  #     - .cache:/root/.cache
  #   platform: linux/arm64

  # indexer:
  #   image: ghcr.io/itmo-call-center-assistant/ragrat/indexer:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   environment:
  #     WEAVIATE_URL: "http://weaviate:8080"
  #   depends_on:
  #     - weaviate

  # worker:
  #   image: ghcr.io/itmo-call-center-assistant/ragrat/worker:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8001:8000"
  #   env_file:
  #     - .env

volumes:
  qdrant_storage:
  weaviate_data:
  transformers_cache:
